### ISSUE TITLE
StackBlitz + jinqu broken

### ISSUE THREAD

**Issue by solenya-group** [jin-qu/jinqu#15]
Hi Umut,

Just noticed jinqu appears to not be playing nicely with StackBlitz:
https://stackblitz.com/edit/min-4zwq1w?file=index.ts

If you comment out the "import jinqu" it works.

Thanks,
Ben

**Comment by umutozel** [comment]
Hi Ben,

Thanks for the feedback, will be looking into it.

**Comment by umutozel** [comment]
I couldn't find the problem, I can run karma tests on my mac, linux and windows (with IE). The error occurs only on StackBlitz (caused by iterator polyfill).

Some of the dependencies had vulnerabilities, so I fixed them and published a minor version (0.6.3) and tried on StackBlitz, no luck. Now I got curious.

**Comment by umutozel** [comment]
Hi Ben,

I removed polyfills/shims from Jinqu package, but still using them on dev. environment and added implementing instructions to the readme. Now StackBlitz is working (with 0.7.0 package).

**Comment by solenya-group** [comment]
Nice, tested it - it's working.
